// Generated by CoffeeScript 1.3.3
(function() {
  var Module,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Module = (function(_super) {

    __extends(Module, _super);

    function Module() {
      return;
    }

    return Module;

  })(Social);

}).call(this);
