// Generated by CoffeeScript 1.3.3
(function() {
  var ArrayProto, ObjProto, So, Social, addToWrapper, breaker, escapeRegExp, hasOwnProperty, idCounter, nativeEvery, nativeFilter, nativeForEach, nativeIndexOf, nativeIsArray, nativeKeys, nativeLastIndexOf, nativeMap, nativeReduce, nativeReduceRight, nativeSome, previousSocial, propertyIsEnumerable, result, root, slice, toString, unshift, wrapper,
    __hasProp = {}.hasOwnProperty;

  root = this;

  previousSocial = root.Social;

  breaker = typeof StopIteration === 'undefined' ? '__break__' : StopIteration;

  escapeRegExp = function(string) {
    return string.replace(/([.*+?^${}()|[\]\/\\])/g, '\\$1');
  };

  ArrayProto = Array.prototype;

  ObjProto = Object.prototype;

  slice = ArrayProto.slice;

  unshift = ArrayProto.unshift;

  toString = ObjProto.toString;

  hasOwnProperty = ObjProto.hasOwnProperty;

  propertyIsEnumerable = ObjProto.propertyIsEnumerable;

  nativeForEach = ArrayProto.forEach;

  nativeMap = ArrayProto.map;

  nativeReduce = ArrayProto.reduce;

  nativeReduceRight = ArrayProto.reduceRight;

  nativeFilter = ArrayProto.filter;

  nativeEvery = ArrayProto.every;

  nativeSome = ArrayProto.some;

  nativeIndexOf = ArrayProto.indexOf;

  nativeLastIndexOf = ArrayProto.lastIndexOf;

  nativeIsArray = Array.isArray;

  nativeKeys = Object.keys;

  Social = function(obj) {
    return new wrapper(obj);
  };

  if (typeof exports !== 'undefined') {
    exports.Social = Social;
  }

  root.Social = So = Social;

  So.VERSION = '0.1';

  So.util.each = function(obj, iterator, context) {
    var i, key, val, _i, _ref;
    try {
      if (nativeForEach && obj.forEach === nativeForEach) {
        obj.forEach(iterator, context);
      } else if (So.util.isNumber(obj.length)) {
        for (i = _i = 0, _ref = obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          iterator.call(context, obj[i], i, obj);
        }
      } else {
        for (key in obj) {
          if (!__hasProp.call(obj, key)) continue;
          val = obj[key];
          iterator.call(context, val, key, obj);
        }
      }
    } catch (e) {
      if (e !== breaker) {
        throw e;
      }
    }
    return obj;
  };

  So.util.map = function(obj, iterator, context) {
    var results;
    if (nativeMap && obj.map === nativeMap) {
      return obj.map(iterator, context);
    }
    results = [];
    So.util.each(obj, function(value, index, list) {
      return results.push(iterator.call(context, value, index, list));
    });
    return results;
  };

  So.util.reduce = function(obj, iterator, memo, context) {
    if (nativeReduce && obj.reduce === nativeReduce) {
      if (context) {
        iterator = So.util.bind(iterator, context);
      }
      return obj.reduce(iterator, memo);
    }
    So.util.each(obj, function(value, index, list) {
      return memo = iterator.call(context, memo, value, index, list);
    });
    return memo;
  };

  So.util.reduceRight = function(obj, iterator, memo, context) {
    var reversed;
    if (nativeReduceRight && obj.reduceRight === nativeReduceRight) {
      if (context) {
        iterator = So.util.bind(iterator, context);
      }
      return obj.reduceRight(iterator, memo);
    }
    reversed = So.util.clone(So.util.toArray(obj)).reverse();
    return So.util.reduce(reversed, iterator, memo, context);
  };

  So.util.detect = function(obj, iterator, context) {
    var result;
    result = null;
    So.util.each(obj, function(value, index, list) {
      if (iterator.call(context, value, index, list)) {
        result = value;
        return So.util.breakLoop();
      }
    });
    return result;
  };

  So.util.filter = function(obj, iterator, context) {
    var results;
    if (nativeFilter && obj.filter === nativeFilter) {
      return obj.filter(iterator, context);
    }
    results = [];
    So.util.each(obj, function(value, index, list) {
      if (iterator.call(context, value, index, list)) {
        return results.push(value);
      }
    });
    return results;
  };

  So.util.reject = function(obj, iterator, context) {
    var results;
    results = [];
    So.util.each(obj, function(value, index, list) {
      if (!iterator.call(context, value, index, list)) {
        return results.push(value);
      }
    });
    return results;
  };

  So.util.every = function(obj, iterator, context) {
    var result;
    iterator || (iterator = So.util.identity);
    if (nativeEvery && obj.every === nativeEvery) {
      return obj.every(iterator, context);
    }
    result = true;
    So.util.each(obj, function(value, index, list) {
      if (!(result = result && iterator.call(context, value, index, list))) {
        return So.util.breakLoop();
      }
    });
    return result;
  };

  So.util.some = function(obj, iterator, context) {
    var result;
    iterator || (iterator = So.util.identity);
    if (nativeSome && obj.some === nativeSome) {
      return obj.some(iterator, context);
    }
    result = false;
    So.util.each(obj, function(value, index, list) {
      if ((result = iterator.call(context, value, index, list))) {
        return So.util.breakLoop();
      }
    });
    return result;
  };

  So.util.include = function(obj, target) {
    var key, val;
    if (nativeIndexOf && obj.indexOf === nativeIndexOf) {
      return So.util.indexOf(obj, target) !== -1;
    }
    for (key in obj) {
      if (!__hasProp.call(obj, key)) continue;
      val = obj[key];
      if (val === target) {
        return true;
      }
    }
    return false;
  };

  So.util.invoke = function(obj, method) {
    var args, val, _i, _len, _results;
    args = So.util.rest(arguments, 2);
    _results = [];
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      val = obj[_i];
      _results.push((method ? val[method] : val).apply(val, args));
    }
    return _results;
  };

  So.util.pluck = function(obj, key) {
    return So.util.map(obj, function(val) {
      return val[key];
    });
  };

  So.util.max = function(obj, iterator, context) {
    var result;
    if (!iterator && So.util.isArray(obj)) {
      return Math.max.apply(Math, obj);
    }
    result = {
      computed: -Infinity
    };
    So.util.each(obj, function(value, index, list) {
      var computed;
      computed = iterator ? iterator.call(context, value, index, list) : value;
      return computed >= result.computed && (result = {
        value: value,
        computed: computed
      });
    });
    return result.value;
  };

  So.util.min = function(obj, iterator, context) {
    var result;
    if (!iterator && So.util.isArray(obj)) {
      return Math.min.apply(Math, obj);
    }
    result = {
      computed: Infinity
    };
    So.util.each(obj, function(value, index, list) {
      var computed;
      computed = iterator ? iterator.call(context, value, index, list) : value;
      return computed < result.computed && (result = {
        value: value,
        computed: computed
      });
    });
    return result.value;
  };

  So.util.sortBy = function(obj, iterator, context) {
    return So.util.pluck((So.util.map(obj, function(value, index, list) {
      return {
        value: value,
        criteria: iterator.call(context, value, index, list)
      };
    })).sort(function(left, right) {
      var a, b;
      a = left.criteria;
      b = right.criteria;
      if (a < b) {
        return -1;
      } else if (a > b) {
        return 1;
      } else {
        return 0;
      }
    }), 'value');
  };

  So.util.sortedIndex = function(array, obj, iterator) {
    var high, low, mid;
    iterator || (iterator = So.util.identity);
    low = 0;
    high = array.length;
    while (low < high) {
      mid = (low + high) >> 1;
      if (iterator(array[mid]) < iterator(obj)) {
        low = mid + 1;
      } else {
        high = mid;
      }
    }
    return low;
  };

  So.util.toArray = function(iterable) {
    if (!iterable) {
      return [];
    }
    if (iterable.toArray) {
      return iterable.toArray();
    }
    if (So.util.isArray(iterable)) {
      return iterable;
    }
    if (So.util.isArguments(iterable)) {
      return slice.call(iterable);
    }
    return So.util.values(iterable);
  };

  So.util.size = function(obj) {
    return So.util.toArray(obj).length;
  };

  So.util.first = function(array, n, guard) {
    if (n && !guard) {
      return slice.call(array, 0, n);
    } else {
      return array[0];
    }
  };

  So.util.rest = function(array, index, guard) {
    return slice.call(array, So.util.isUndefined(index) || guard ? 1 : index);
  };

  So.util.last = function(array) {
    return array[array.length - 1];
  };

  So.util.compact = function(array) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      item = array[_i];
      if (item) {
        _results.push(item);
      }
    }
    return _results;
  };

  So.util.flatten = function(array) {
    return So.util.reduce(array, function(memo, value) {
      if (So.util.isArray(value)) {
        return memo.concat(So.util.flatten(value));
      }
      memo.push(value);
      return memo;
    }, []);
  };

  So.util.without = function(array) {
    var val, values, _i, _len, _ref, _results;
    values = So.util.rest(arguments);
    _ref = So.util.toArray(array);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      val = _ref[_i];
      if (!So.util.include(values, val)) {
        _results.push(val);
      }
    }
    return _results;
  };

  So.util.uniq = function(array, isSorted) {
    var el, i, memo, _i, _len, _ref;
    memo = [];
    _ref = So.util.toArray(array);
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      el = _ref[i];
      if (i === 0 || (isSorted === true ? So.util.last(memo) !== el : !So.util.include(memo, el))) {
        memo.push(el);
      }
    }
    return memo;
  };

  So.util.intersect = function(array) {
    var rest;
    rest = So.util.rest(arguments);
    return So.util.select(So.util.uniq(array), function(item) {
      return So.util.all(rest, function(other) {
        return So.util.indexOf(other, item) >= 0;
      });
    });
  };

  So.util.zip = function() {
    var i, length, results, _i;
    length = So.util.max(So.util.pluck(arguments, 'length'));
    results = new Array(length);
    for (i = _i = 0; 0 <= length ? _i < length : _i > length; i = 0 <= length ? ++_i : --_i) {
      results[i] = So.util.pluck(arguments, String(i));
    }
    return results;
  };

  So.util.indexOf = function(array, item) {
    var i, l;
    if (nativeIndexOf && array.indexOf === nativeIndexOf) {
      return array.indexOf(item);
    }
    i = 0;
    l = array.length;
    while (l - i) {
      if (array[i] === item) {
        return i;
      } else {
        i++;
      }
    }
    return -1;
  };

  So.util.lastIndexOf = function(array, item) {
    var i;
    if (nativeLastIndexOf && array.lastIndexOf === nativeLastIndexOf) {
      return array.lastIndexOf(item);
    }
    i = array.length;
    while (i) {
      if (array[i] === item) {
        return i;
      } else {
        i--;
      }
    }
    return -1;
  };

  So.util.range = function(start, stop, step) {
    var a, i, idx, len, range, solo;
    a = arguments;
    solo = a.length <= 1;
    i = start = solo ? 0 : a[0];
    stop = solo ? a[0] : a[1];
    step = a[2] || 1;
    len = Math.ceil((stop - start) / step);
    if (len <= 0) {
      return [];
    }
    range = new Array(len);
    idx = 0;
    while (true) {
      if ((step > 0 ? i - stop : stop - i) >= 0) {
        return range;
      }
      range[idx] = i;
      idx++;
      i += step;
    }
  };

  So.util.bind = function(func, obj) {
    var args;
    args = So.util.rest(arguments, 2);
    return function() {
      return func.apply(obj || root, args.concat(arguments));
    };
  };

  So.util.bindAll = function(obj) {
    var funcs;
    funcs = arguments.length > 1 ? So.util.rest(arguments) : So.util.functions(obj);
    So.util.each(funcs, function(f) {
      return obj[f] = So.util.bind(obj[f], obj);
    });
    return obj;
  };

  So.util.delay = function(func, wait) {
    var args;
    args = So.util.rest(arguments, 2);
    return setTimeout((function() {
      return func.apply(func, args);
    }), wait);
  };

  So.util.memoize = function(func, hasher) {
    var memo;
    memo = {};
    hasher || (hasher = So.util.identity);
    return function() {
      var key;
      key = hasher.apply(this, arguments);
      if (key in memo) {
        return memo[key];
      }
      return memo[key] = func.apply(this, arguments);
    };
  };

  So.util.defer = function(func) {
    return So.util.delay.apply(_, [func, 1].concat(So.util.rest(arguments)));
  };

  So.util.wrap = function(func, wrapper) {
    return function() {
      return wrapper.apply(wrapper, [func].concat(arguments));
    };
  };

  So.util.compose = function() {
    var funcs;
    funcs = arguments;
    return function() {
      var args, i, _i, _ref;
      args = arguments;
      for (i = _i = _ref = funcs.length - 1; _i >= 0; i = _i += -1) {
        args = [funcs[i].apply(this, args)];
      }
      return args[0];
    };
  };

  So.util.keys = nativeKeys || function(obj) {
    var key, val, _results;
    if (So.util.isArray(obj)) {
      return So.util.range(0, obj.length);
    }
    _results = [];
    for (key in obj) {
      val = obj[key];
      _results.push(key);
    }
    return _results;
  };

  So.util.values = function(obj) {
    return So.util.map(obj, So.util.identity);
  };

  So.util.functions = function(obj) {
    return So.util.filter(So.util.keys(obj), function(key) {
      return So.util.isFunction(obj[key]);
    }).sort();
  };

  So.util.extend = function(obj) {
    var key, source, val, _i, _len, _ref;
    _ref = So.util.rest(arguments);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      source = _ref[_i];
      for (key in source) {
        val = source[key];
        obj[key] = val;
      }
    }
    return obj;
  };

  So.util.clone = function(obj) {
    if (So.util.isArray(obj)) {
      return obj.slice(0);
    }
    return So.util.extend({}, obj);
  };

  So.util.tap = function(obj, interceptor) {
    interceptor(obj);
    return obj;
  };

  So.util.isEqual = function(a, b) {
    var aKeys, atype, bKeys, btype, key, val;
    if (a === b) {
      return true;
    }
    atype = typeof a;
    btype = typeof b;
    if (atype !== btype) {
      return false;
    }
    if (a == b) {
      return true;
    }
    if ((!a && b) || (a && !b)) {
      return false;
    }
    if (a.isEqual) {
      return a.isEqual(b);
    }
    if (So.util.isDate(a) && So.util.isDate(b)) {
      return a.getTime() === b.getTime();
    }
    if (So.util.isNaN(a) && So.util.isNaN(b)) {
      return false;
    }
    if (So.util.isRegExp(a) && So.util.isRegExp(b)) {
      return a.source === b.source && a.global === b.global && a.ignoreCase === b.ignoreCase && a.multiline === b.multiline;
    }
    if (atype !== 'object') {
      return false;
    }
    if (a.length && (a.length !== b.length)) {
      return false;
    }
    aKeys = So.util.keys(a);
    bKeys = So.util.keys(b);
    if (aKeys.length !== bKeys.length) {
      return false;
    }
    for (key in a) {
      val = a[key];
      if (!(key in b) || !So.util.isEqual(val, b[key])) {
        return false;
      }
    }
    return true;
  };

  So.util.isEmpty = function(obj) {
    var key;
    if (So.util.isArray(obj) || So.util.isString(obj)) {
      return obj.length === 0;
    }
    for (key in obj) {
      if (!__hasProp.call(obj, key)) continue;
      return false;
    }
    return true;
  };

  So.util.isElement = function(obj) {
    return obj && obj.nodeType === 1;
  };

  So.util.isArray = nativeIsArray || function(obj) {
    return !!(obj && obj.concat && obj.unshift && !obj.callee);
  };

  So.util.isArguments = function(obj) {
    return obj && obj.callee;
  };

  So.util.isFunction = function(obj) {
    return !!(obj && obj.constructor && obj.call && obj.apply);
  };

  So.util.isString = function(obj) {
    return !!(obj === '' || (obj && obj.charCodeAt && obj.substr));
  };

  So.util.isNumber = function(obj) {
    return (obj === +obj) || toString.call(obj) === '[object Number]';
  };

  So.util.isBoolean = function(obj) {
    return obj === true || obj === false;
  };

  So.util.isDate = function(obj) {
    return !!(obj && obj.getTimezoneOffset && obj.setUTCFullYear);
  };

  So.util.isRegExp = function(obj) {
    return !!(obj && obj.exec && (obj.ignoreCase || obj.ignoreCase === false));
  };

  So.util.isNaN = function(obj) {
    return So.util.isNumber(obj) && window.isNaN(obj);
  };

  So.util.isNull = function(obj) {
    return obj === null;
  };

  So.util.isUndefined = function(obj) {
    return typeof obj === 'undefined';
  };

  So.util.noConflict = function() {
    root._ = previousSocial;
    return this;
  };

  So.util.identity = function(value) {
    return value;
  };

  So.util.times = function(n, iterator, context) {
    var i, _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      _results.push(iterator.call(context, i));
    }
    return _results;
  };

  So.util.breakLoop = function() {
    throw breaker;
  };

  So.util.mixin = function(obj) {
    var name, _i, _len, _ref, _results;
    _ref = So.util.functions(obj);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      _results.push(addToWrapper(name, _[name] = obj[name]));
    }
    return _results;
  };

  idCounter = 0;

  So.util.uniqueId = function(prefix) {
    return (prefix || '') + idCounter++;
  };

  So.util.templateSettings = {
    start: '<%',
    end: '%>',
    interpolate: /<%=(.+?)%>/g
  };

  So.util.template = function(str, data) {
    var c, endMatch, fn;
    c = So.util.templateSettings;
    endMatch = new RegExp("'(?=[^" + c.end.substr(0, 1) + "]*" + escapeRegExp(c.end) + ")", "g");
    fn = new Function('obj', 'var p=[],print=function(){p.push.apply(p,arguments);};' + 'with(obj||{}){p.push(\'' + str.replace(/\r/g, '\\r').replace(/\n/g, '\\n').replace(/\t/g, '\\t').replace(endMatch, "✄").split("'").join("\\'").split("✄").join("'").replace(c.interpolate, "',$1,'").split(c.start).join("');").split(c.end).join("p.push('") + "');}return p.join('');");
    if (data) {
      return fn(data);
    } else {
      return fn;
    }
  };

  So.util.forEach = So.util.each;

  So.util.foldl = So.util.inject = So.util.reduce;

  So.util.foldr = So.util.reduceRight;

  So.util.select = So.util.filter;

  So.util.all = So.util.every;

  So.util.any = So.util.some;

  So.util.contains = So.util.include;

  So.util.head = So.util.first;

  So.util.tail = So.util.rest;

  So.util.methods = So.util.functions;

  wrapper = function(obj) {
    this._wrapped = obj;
    return this;
  };

  result = function(obj, chain) {
    if (chain) {
      return _(obj).chain();
    } else {
      return obj;
    }
  };

  addToWrapper = function(name, func) {
    return wrapper.prototype[name] = function() {
      var args;
      args = So.util.toArray(arguments);
      unshift.call(args, this._wrapped);
      return result(func.apply(_, args), this._chain);
    };
  };

  So.util.mixin(_);

  So.util.each(['pop', 'push', 'reverse', 'shift', 'sort', 'splice', 'unshift'], function(name) {
    var method;
    method = Array.prototype[name];
    return wrapper.prototype[name] = function() {
      method.apply(this._wrapped, arguments);
      return result(this._wrapped, this._chain);
    };
  });

  So.util.each(['concat', 'join', 'slice'], function(name) {
    var method;
    method = Array.prototype[name];
    return wrapper.prototype[name] = function() {
      return result(method.apply(this._wrapped, arguments), this._chain);
    };
  });

  wrapper.prototype.chain = function() {
    this._chain = true;
    return this;
  };

  wrapper.prototype.value = function() {
    return this._wrapped;
  };

}).call(this);
